### ISSUE TITLE
Specifying the use of the `key` variable for `Serverside` objects in the documentation

### ISSUE THREAD

**Issue by matt-sd-watson** [emilhe/dash-extensions#302]
I have created a Flask and dash app that uses dash components, including the `ServersideOutputTransform`, to cache and store large dictionaries of arrays. The component works very well for my requirements. 

I recently discovered that specifying the same `key` string for `Serverside` objects in different callbacks allows the transform to overwrite the previous pickle files in the specified backend directory. Previously, without any unique key, the transform would create a new pickled object, and this would cause a lot of duplicate data writing to the temporary cache, as well as cause the temporary cache to become populated very quickly with many pickle files. 

I would suggest explicitly explaining in the documentation how the `key` parameter for `Serverside` objects works, as this can save a great deal of disk space when `Serverside` objects are constantly being updated from different callbacks. Now, when using a unique key, I can drastically reduce the amount of disk space required for my `Serverside` objects in session.

**Comment by emilhe** [comment]
I have added the following paragraph to the docs,

### Keys

Per default, the `Serverside` object ge nerates a new unique key for every callback invocation to ensure that data is never shared between invocations and/or sessions. However, if this is not a requirement, using a fixed key will reduce the data usage of the cache significantly, as only one copy of the data will be stored (instead of one per callback invocation).
